export interface Product {
    id: number
    title: string
    brand: string
    options: string
    image: string
    category: string
    brandImage:string
    route:string
  }
  
  export const products: Product[] = [
    {
      id: 1,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Wardrobes",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 2,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Wardrobes",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 3,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Wardrobes",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 4,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Beds",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 5,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Beds",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 6,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Beds",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 7,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Beds",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 8,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Beds",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 9,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Dining Sets",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 10,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Dining Sets",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 11,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Dining Sets",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 12,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Dining Sets",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 13,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Sofas",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 14,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Sofas",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 15,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Sofas",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },
    {
      id: 16,
      title: "Contemporary & sleek",
      brand: "woodsworth",
      options: "1000+ Options",
      image: "https://res.cloudinary.com/dk6m1qejk/image/upload/v1730747519/firefly/nyv8rkifj0lma5xldqjx.png",
      category: "Sofas",
      brandImage:"https://plchldr.co/i/500x250?bg=111111",
      route:"#",
    },

  ]
  
  export const categories = ["Wardrobes", "Beds", "Dining Sets", "Sofas"]